<a href="https://colab.research.google.com/github/Rhea3010/Big_data/blob/main/labeval_mca2_202301046.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr1=np.array([10,52,62,16,16,54,453])

In [13]:
#sorted array
arr2=np.sort(arr1)
print(arr2)

[ 10  16  16  52  54  62 453]


In [10]:
#indices of sorted array
np.argsort(arr1)

array([0, 3, 4, 1, 5, 2, 6])

In [12]:
#4 smallest elements
print(arr2[0:4])

[10 16 16 52]


In [14]:
#5 largest elements
print(arr2[2:])

[ 16  52  54  62 453]
